logging:
    level:
        org:
            springframework:
                security: DEBUG
            hibernate:
                SQL: DEBUG

spring:
    mvc:
        pathmatch: ##??? ??? ???
            matching-strategy: ant_path_matcher